DELETE http://localhost:3000/api?isbn=123456
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cGlyZV9kYXRlIjoxNjgyOTM1OTI5MjQzLCJpYXQiOjE2ODI3NjMxMjl9.H8nvTg6gE5FkczcnKzpd2b3UAPl4gYn5Gi4GQB-8ay0"
}